server:
  tomcat:
    connection-timeout: 300000    # 5 minutos
  servlet:
    async-timeout: 300000         # 5 minutos para requests assíncronos
  port: ${PORT:8097}

spring:
  application:
    name: narrative-api

  config:
    import:
      - optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: narrative_db
      username: ${MONGO_ROOT_USER:admin}
      password: ${MONGO_ROOT_PASS}
      authentication-database: admin

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.0-flash
            temperature: 0.8
            max-output-tokens: 300

app:
  auth:
    token-secret: ${JWT_TOKEN_SECRET}
    token-expiration-msec: 900000
    refresh-token-expiration-msec: 604800000

  narrative:
    max-historico-mensagens: 20

logging:
  level:
    root: INFO
    br.com.study.narrativeapi: DEBUG